### ISSUE TITLE
Clutter-CRITICAL Logs when starting Skype with this plugin enabled

### ISSUE THREAD

**Issue by Damiox** [chrisss404/gnome-shell-ext-SkypeNotification#52]
- Debian Jessie 3.16.0-4-amd64
- Gnome 3.14.2
- Problem: When starting Skype (with this plugin enabled), the following errors are logged in /var/log/syslog:

Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Feb  3 18:32:25 skeletor gnome-session[859]: (gnome-shell:992): Clutter-CRITICAL **: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed

If I disable the plugin, those errors dissapear.
Everything works fine anyways, but I'm wondering what those log errors are referring to.

Thanks
Damian

**Comment by chrisss404** [comment]
Hi Damian,

thanks for reporting. Unfortunately, I have no idea what is causing this error, because I was not able to reproduce it on:

* Debian Jessie 8.0 RC1 (3.16.0-4-586)
* Gnome 3.14.2

and

* Fedora 21 (3.18.3-201.fc21.x86_64)
* Gnome 3.14.3

Best regards,
Christian

**Comment by chrisss404** [comment]
gs3.14 is no longer supported
