### ISSUE TITLE
Icon does not indicate new messages

### ISSUE THREAD

**Issue by bk138** [chrisss404/gnome-shell-ext-SkypeNotification#53]
Hi there, me again.
While the icon now properly shows up when Skype is started, there still is an issue WRT incoming messages: the icon does not show the orange exclamation mark thingy. 

The icon *does* change when I change status in Skype though.

The events are activated in Skype prefs, but set to no-sound and no-notification.

**Comment by chrisss404** [comment]
Hi,

try to execute the following command:

    python ~/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e"ChatIncoming" -n"Test" -f"%fname" -p"%fpath" -m"hello" -s"%fsize" -u"%sskype"

you should get a notification that says "Test hello", additionally the orange exclamation mark should appear.

If that is the case, your Skype is configured wrongly. Go to `Options` > `Notifications` > `Chat Message Received`, activate `Advanced View`, make sure that `Execute the following script` is checked, and the input field contains the following text: `python /home/*YOUR_USERNAME*/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e"%type" -n"%sname" -f"%fname" -p"%fpath" -m"%smessage" -s"%fsize" -u"%sskype"`.

Otherwise, I am not sure what is causing your problem.

Best regards,
Christian

**Comment by bk138** [comment]
Well this shows the orange exclamation mark when I hit "test event". How to make the '!' disappear afterwards? Clicking on the icon shows Skype, but the '!' is still there...

I can send in my Skype config if needed...

**Comment by chrisss404** [comment]
The orange exclamation mark should go away, if you open/focus a chat window.

Yes, you can send me your configuration file, but everything regarding it should be done automatically (open the extension's options and toggle the `native notifications` option to get the correct settings, default: active). I think that the extension is not able to access your Skype config file for some strange reason, maybe you have special characters in your Skype user name, or have a problem with file permissions?

**Comment by bk138** [comment]
Mhh file mode is 600

```
bk@bunker2:~$ ls -la .Skype/dont.mind..#/config.xml 
-rw------- 1 bk bk 13979 Feb 13 13:07 .Skype/dont.mind..#/config.xml
```

What config files does your extension parse?

**Comment by chrisss404** [comment]
Strange, permissions and config file are correct.

    ls -al .Skype/[USERNAME]/config.xml
    -rw-------. 1 chris chris 18272 Feb 13 16:32 .Skype/[USERNAME]/config.xml

Here is the relevant part of my config, but I have no idea why it is not added automatically (if it is missing):

    <?xml version="1.0"?>
    <config version="1.0" serial="5912" timestamp="1423840935.26">
      <Lib>
        .
        .
        .
      </Lib>
      <UI>
        <API>
          <Authorizations>GnomeShellExtension</Authorizations>
          <BlockedPrograms></BlockedPrograms>
        </API>
        <AutoUpdate>0</AutoUpdate>
        <ConversationsWindow>
          .
          .
          .
        </ConversationsWindow>
        <Live>
          .
          .
          .
        </Live>
        <Notifications>
          <Enable>
            <Scripts>
              <Birthday>1</Birthday>
              <CallMissed>1</CallMissed>
              <ChatIncoming>1</ChatIncoming>
              <ChatJoined>0</ChatJoined>
              <ChatOutgoing>0</ChatOutgoing>
              <ChatParted>0</ChatParted>
              <ContactAdded>1</ContactAdded>
              <ContactAuthRequest>1</ContactAuthRequest>
              <ContactDeleted>1</ContactDeleted>
              <ContactOffline>1</ContactOffline>
              <ContactOnline>1</ContactOnline>
              <OurBirthday>1</OurBirthday>
              <SMSFailed>1</SMSFailed>
              <SMSSent>1</SMSSent>
              <TransferComplete>1</TransferComplete>
              <TransferFailed>1</TransferFailed>
              <TransferRequest>1</TransferRequest>
              <VoicemailReceived>1</VoicemailReceived>
              <VoicemailSent>0</VoicemailSent>
            </Scripts>
          </Enable>
          <Scripts>
            <Birthday>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</Birthday>
            <CallMissed>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</CallMissed>
            <ChatIncoming>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ChatIncoming>
            <ChatJoined>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ChatJoined>
            <ChatOutgoing>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ChatOutgoing>
            <ChatParted>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ChatParted>
            <ContactAdded>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ContactAdded>
            <ContactAuthRequest>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ContactAuthRequest>
            <ContactDeleted>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ContactDeleted>
            <ContactOffline>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ContactOffline>
            <ContactOnline>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</ContactOnline>
            <OurBirthday>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</OurBirthday>
            <SMSFailed>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</SMSFailed>
            <SMSSent>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</SMSSent>
            <TransferComplete>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</TransferComplete>
            <TransferFailed>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</TransferFailed>
            <TransferRequest>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</TransferRequest>
            <VoicemailReceived>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</VoicemailReceived>
            <VoicemailSent>python /home/chris/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34; -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;</VoicemailSent>
          </Scripts>
        </Notifications>
        <Notify>
          <Authreq>0</Authreq>
          <Birthday>0</Birthday>
          <CallMissed>0</CallMissed>
          <Chat>0</Chat>
          <ChatJoined>0</ChatJoined>
          <ChatOutgoing>0</ChatOutgoing>
          <ChatParted>0</ChatParted>
          <ContactAdded>0</ContactAdded>
          <ContactDeleted>0</ContactDeleted>
          <Offline>0</Offline>
          <Online>0</Online>
          <OurBirthday>0</OurBirthday>
          <SMSFailed>0</SMSFailed>
          <SMSSent>0</SMSSent>
          <TransferComplete>0</TransferComplete>
          <TransferFailed>0</TransferFailed>
          <TransferRequest>0</TransferRequest>
          <VoicemailReceived>0</VoicemailReceived>
          <VoicemailSent>0</VoicemailSent>
        </Notify>
        <Sound>
          .
          .
          .
        </Sound>
        <TransferWindow>
          .
          .
          .
        </TransferWindow>
      </UI>
    </config>

**Comment by bk138** [comment]
Well I have
```
   <Notifications>
      <Enable>
        <CallBusy>0</CallBusy>
        <CallConnecting>0</CallConnecting>
        <CallFailed>0</CallFailed>
        <CallHangup>0</CallHangup>
        <CallHold>0</CallHold>
        <CallMissed>0</CallMissed>
        <CallRemoteHangup>0</CallRemoteHangup>
        <CallResume>0</CallResume>
        <CallRingingOut>0</CallRingingOut>
        <ChatIncoming>1</ChatIncoming>
        <ChatIncomingInitial>1</ChatIncomingInitial>
        <ChatJoined>0</ChatJoined>
        <ChatOutgoing>1</ChatOutgoing>
        <ChatParted>0</ChatParted>
        <ContactAdded>0</ContactAdded>
        <ContactAuthRequest>0</ContactAuthRequest>
        <ContactDeleted>0</ContactDeleted>
        <ContactOffline>0</ContactOffline>
        <ContactOnline>0</ContactOnline>
        <NotifySystem>
          <Chat>0</Chat>
        </NotifySystem>
        <OurBirthday>0</OurBirthday>
        <SMSFailed>0</SMSFailed>
        <SMSSent>0</SMSSent>
        <Scripts>
          <ChatIncoming>1</ChatIncoming>
        </Scripts>
        <SkypeLogin>0</SkypeLogin>
        <SkypeLoginFailed>0</SkypeLoginFailed>
        <SkypeLogout>0</SkypeLogout>
        <TransferComplete>0</TransferComplete>
        <TransferFailed>0</TransferFailed>
        <VoicemailReceived>0</VoicemailReceived>
        <VoicemailSent>0</VoicemailSent>
      </Enable>
      <Scripts>
        <ChatIncoming>python /home/bk/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e&#34;%type&#34;
 -n&#34;%sname&#34; -f&#34;%fname&#34; -p&#34;%fpath&#34; -m&#34;%smessage&#34; -s&#34;%fsize&#34; -u&#34;%sskype&#34;&#10;</ChatIncoming>
      </Scripts>
    </Notifications>
```
NB that I added the ChatIncoming script manually as per your advice. This and the others should have been added automatically?

**Comment by chrisss404** [comment]
Yes, this should have been added automatically on the first run. You can open the extension's preferences by running following command in a terminal `gnome-shell-extension-prefs SkypeNotification@chrisss404.gmail.com`.
Then toggle the `Native notifications` switch and a config update should be triggered. If the switch is active, you should get the exclamation mark, which indicates new messages (if Skype's chat window is focused, the indicator does not appear).

Btw. the config you have posted worked for me.

**Comment by bk138** [comment]
Yes, the config works. But not out of the box: the python calls were not added to the config. Also, the native notifications toggle did not add the python calls to the config file.

**Comment by chrisss404** [comment]
As said before, I have no idea why it is not added automatically to your config file. It works for me on a fresh Fedora and Debian installation. Additionally, it does not seem that there is an error message emitted (right?), which makes it even harder to locate the problem.

Sorry, I can't help you.

**Comment by bk138** [comment]
Well it works by adding the python call manually so let's consider this kinda fixed.
