### ISSUE TITLE
Icons provided by the extension are not shown

### ISSUE THREAD

**Issue by fehu** [chrisss404/gnome-shell-ext-SkypeNotification#54]
![skype-icon-fail](https://cloud.githubusercontent.com/assets/540707/6097537/1d659836-af87-11e4-9df4-e9d6473ddcdc.png)

After updating to GNOME Shell 3.14.3 none of the extension's icons shows up. There is some gnome stub icon instead.

I did reinstall the extension from master snapshot; also tried disabling the rest of extension I have.

**Comment by chrisss404** [comment]
Thanks for reporting, please check if the latest commit resolves the problem.

**Comment by fehu** [comment]
It did. Thank you.
