### ISSUE TITLE
No indication that the secondary Skype is active

### ISSUE THREAD

**Issue by kostich** [chrisss404/gnome-shell-ext-SkypeNotification#56]
When I run another instance of Skype with 'nohup skype -s && disown', there's no information about that other Skype running in the extension interface.

**Comment by chrisss404** [comment]
Sorry multiple instances are not supported and I am not sure, if it would be possible. This extension is listening to dbus messages, which are emitted by Skype, and I have no idea, if these messages are distinguishable when there are multiple instances.
