### ISSUE TITLE
Disable original Skype Tray Icon

### ISSUE THREAD

**Issue by Tuchkata** [chrisss404/gnome-shell-ext-SkypeNotification#58]
Is there a way to disable the original Skype Tray Icon when the extension is installed and is working? When using it with other extensions, which put the tray icons in the top panel, there are two Skype tray icons.

**Comment by chrisss404** [comment]
I have three possible solutions for you, but you won't like any of them:

1. go to the extension settings and disable the top bar icon of this extension
2. disable the extension, which puts the tray icons into the top panel
3. ask the author of the other extension to hide the original Skype icon if this extension is enabled

Unfortunetly there is no clean solution for the issue in the way you describe it.

**Comment by chrisss404** [comment]
I suppose you are using this extension: https://extensions.gnome.org/extension/495/topicons/?
If that is the case, you can add the following code to the end of the function `onTrayIconAdded` in ` ~/.local/share/gnome-shell/extensions/topIcons@adel.gadllah@gmail.com/extension.js`.

    try {
        let uuid = "SkypeNotification@chrisss404.gmail.com";
        if(wmClass == "skype" && imports.misc.extensionUtils.extensions[uuid].state == 1) {
            icon.get_parent().hide();
        }
    } catch(e) {}

Feel free to ask the author of TopIcons to add this code snippet to his extension.

**Comment by Tuchkata** [comment]
Yes, this is the extension that I am using. I will try it today evening and I will tell you if this one is solving my issue.

**Comment by simonwjackson** [comment]
@chrisss404: How did you obtain the UUID for skype?

**Comment by chrisss404** [comment]
You can discover the UUID in the extension's metadata file, see:
https://github.com/chrisss404/gnome-shell-ext-SkypeNotification/blob/master/SkypeNotification%40chrisss404.gmail.com/metadata.json#L4

**Comment by adriaanb** [comment]
Sorry for bringing this up again, but the solution you suggested works only partially, e.g. when more than the Skype icon itself are running in the tray. I use the toptray extension to use it with gtk-redshift, but while redshift is not running the Skype icon is the only other tray item present. In that scenario, your suggested code renders it invisible, but it is still "clickable" and sort of overlays the GNOME Shell Skype integration icon - at least when the topicons extension sits right next to the GNOME Shell Skype integration icon (so when I try to click it, it actually activates the Skype system tray context menu, which shows up in the bottom left corner of the screen). Is there any alternative way to disable the Skype tray icon?

**Comment by chrisss404** [comment]
Check, if destroying the click proxy solves the problem:

    try {
        let uuid = "SkypeNotification@chrisss404.gmail.com";
        if(wmClass == "skype" && imports.misc.extensionUtils.extensions[uuid].state == 1) {
            icon.get_parent().hide();
            icon._clickProxy.destroy();
        }
    } catch(e) {}

**Comment by adriaanb** [comment]
That did indeed fix the issue, thanks a lot!

**Comment by chrisss404** [comment]
Thx to @phocean there is now another solution: upgrade to [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/).

**Comment by Tuchkata** [comment]
TopIcons Plus does the trick, great!
