### ISSUE TITLE
Not alerting on message received...

### ISSUE THREAD

**Issue by PatriqDesigns** [chrisss404/gnome-shell-ext-SkypeNotification#59]
Not sure why but is not alerting...
Im using Fedora 22, and I have DBus python instaled.
When running python ~/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e"ChatIncoming" -n"Test" -f"%fname" -p"%fpath" -m"hello" -s"%fsize" -u"%sskype" I get the notification, and all but whenever I receive a message it just does't work!

**Comment by chrisss404** [comment]
Do the opposite of what is suggested in #9 and you should get your notifications.
