### ISSUE TITLE
don't show some notifications permanent

### ISSUE THREAD

**Issue by pointhi** [chrisss404/gnome-shell-ext-SkypeNotification#61]
Notifications like: ```*** went online``` should be display only a few seconds (and not permanent) in the notification tray.

In my opinion, only notifications for new messages, calls and so on should be displayed permanent until clicked onto it or doing a similar response in the client.

When for example someone went online, this is only a information, and nothing which requires appropriate reaction onto it.

**Comment by chrisss404** [comment]
You are right. However the shell notifications are already set to transient, therefore no action should be necessary. 
A workaround would be to modify the default behavior of the shell notifications. Although I would like to avoid that. What you think?

**Comment by pointhi** [comment]
Hm, For me notifications stay until I clear them:

For example, the ```went online``` and ```went offline``` notification is now more than 15 Minutes old:

![skype_notification](https://cloud.githubusercontent.com/assets/1652144/12715540/2c73dbd0-c8db-11e5-8aad-a8069563f9ad.png)

I would suggest a timeout of about 5-10 Seconds for temporary informations like ```went online```

**Comment by chrisss404** [comment]
Ah, you mean the notification history next to the calendar. I don't know what options are available and what is the default behavior here, therefore I have to look into it.
Do you know an application with notifications behaving the way you desire?

**Comment by pointhi** [comment]
I created a pull request for https://github.com/manjaro/pamac/pull/88 which implemented similar behavior.

When you are using [gtk.NotifyNotification](https://developer.gnome.org/libnotify/unstable/NotifyNotification.html) directly, I can help you with the api.

**Comment by chrisss404** [comment]
Please check the updated notification behavior.

**Comment by pointhi** [comment]
Thx, seems like the bugfix is working.

I'm not sure if this is releated with this bugfix, but when I do a left click onto the tray icon, the message ```skype is ready``` appears for about 1/2 second an then disapears. I would propose the same behaviour as for ```user went online``` now, or simply not showing a notification for that at all.

**Comment by chrisss404** [comment]
It was not related, but it should be fixed with the latest commit.

Please check and have a nice day.

**Comment by pointhi** [comment]
thx, all patches seems to work correctly.
