### ISSUE TITLE
Icon position on topbar

### ISSUE THREAD

**Issue by archdria** [chrisss404/gnome-shell-ext-SkypeNotification#62]
Hi!
Could it be possible to add a position setting?
I was thinking about something like what is implemented in [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons).

I would like the Skype icon to be placed between the keyboard layout and the Network/Volume/Battery system icons.
According to the TopIcons Plus, this position corresponds to number 1.
I think it would be great to have a deterministic position for Skype to appear.

Thanks in advance and keep up with the great job you're doing on this extension.

**Comment by chrisss404** [comment]
Sure.

**Comment by chrisss404** [comment]
Please review.

**Comment by archdria** [comment]
Perfect!

That was really quick! Thank you :D
