### ISSUE TITLE
clicking on the notification to get new message causes skype window is always at the top

### ISSUE THREAD

**Issue by pointhi** [chrisss404/gnome-shell-ext-SkypeNotification#63]
When I get a message, and click onto the notification next to the calendar, The skype window is only staying at the foreground, and I'm not longer able to show an application window before the skype window until I close the skype window and open it not using the "new message" notification.

Desired behaviour:
The skype window shouldn't force to be on the foreground, even another application is clicked to be on focus now.

**Comment by pointhi** [comment]
could you explain the meaning of https://github.com/chrisss404/gnome-shell-ext-SkypeNotification/blob/efa74869b70c292b9ccc74c6c581f3662d05c7a9/SkypeNotification%40chrisss404.gmail.com/skype.js#L831? I haven't validated it, but it likely causes this bug.

**Comment by chrisss404** [comment]
Hi, please report issues only, if they occur in the latest version. I checked recent commits and found that with commit 7ccf8f9076ad4614a456c23a0758d0aae58e3679 the described behavior was no longer reproducable. Is this behavior still apparent for you in the latest version?

**Comment by chrisss404** [comment]
No reaction, I assume the problem is solved.
