### ISSUE TITLE
Which part of code responsible to generate skype.desktop ?

### ISSUE THREAD

**Issue by limkokhole** [chrisss404/gnome-shell-ext-SkypeNotification#65]
My platform is Fedora 21, gnome-session 3.14.0. It doesn't matter if it was deprecated and no longer support, but i'm curious to know the reason.

`journalctl /usr/bin/gnome-session -f` show this error when install:

> gnome-session[3455]: Gjs-Message: JS LOG: Extension "SkypeNotification@chrisss404.gmail.com" had error: Error: Could not find Skype! Make sure that the Desktop entry file 'skype.desktop' is available.

I look at the **skype.js** source code, this is so obvious **skype.desktop** need to exist.
```
        this._skypeApp = Shell.AppSystem.get_default().lookup_app("skype.desktop");
        if(this._skypeApp == null) {
            throw new Error("Could not find Skype! Make sure that the Desktop entry file 'skype.desktop' is available.");
        }

```
I'm not familiar with gnome extension development. But can you point out which portion of your code take responsible to generate this skype.desktop (I grep and earn nothing interest) ? Or is it a new feature in newer gnome shell (> 3.14) which will automatic generate desktop entry ? Is it possible i create this file manually(Or show me your skype.desktop content as reference) ?

**Comment by chrisss404** [comment]
You get the skype.desktop file, if you install skype from https://www.skype.com/. 

    cat /usr/share/applications/skype.desktop 
    [Desktop Entry]
    Name=Skype
    Comment=Skype Internet Telephony
    Exec=skype %U
    Icon=skype.png
    Terminal=false
    Type=Application
    Encoding=UTF-8
    Categories=Network;Application;
    MimeType=x-scheme-handler/skype;
    X-KDE-Protocols=skype

**Comment by chrisss404** [comment]
No reaction, I assume the problem is solved.
