### ISSUE TITLE
Inscrease tray icon size

### ISSUE THREAD

**Issue by Sh1d0w** [chrisss404/gnome-shell-ext-SkypeNotification#66]
Hello,

I really like your plugin. I am using it on Fedora 23 with Gnome 3.18. The tray icon seems too small compared to the other tray icons. 

[![Toolbar](http://s33.postimg.org/78q6nr567/toolbar.png)](http://s33.postimg.org/78q6nr567/toolbar.png)

I tinkered a little bit in the code, but could not find a way to set the tray icon size.

Can you please advice how I can achieve this? I saw your icons are in SVG format and are large enough, however the icon appears with some padding maybe?

Thank you for your time.

**Comment by chrisss404** [comment]
Hi, please check if the latest commit achieves what you are looking for. Have a nice Sunday!

**Comment by Sh1d0w** [comment]
Works like a charm, thanks!
