### ISSUE TITLE
Current API not compatible with Cloud-based chats

### ISSUE THREAD

**Issue by luord** [chrisss404/gnome-shell-ext-SkypeNotification#69]
Entirely an upstream problem but still, you might want to mention (under a "Known Issues" section, probably) that the current Desktop API can't interact with or see cloud-based chats.

I tested everything I could with the API while trying to fix the issue with group chats but cloud-based chats are completely invisible as far I could see. The problem seems to be only with group chats, individual chats still work fine.

The rule of thumb is, when typing `/get name` in a group chat:

* If the result is `name=19:...`, the chat won't work with the API and thus the extension won't see it.
* If the result is `name=#...`, the chat is P2P based and it works fine.

And the desktop client (at least the latest "stable" one, 4.3) creates cloud-based group chats by default so most group chats are invisible to the extension (I had to create the aforementioned P2P chats using the API itself).

**Comment by chrisss404** [comment]
Thank you for your contribution, added the section known issues containing your findings.
