### ISSUE TITLE
the extension doesn't shows alert icon

### ISSUE THREAD

**Issue by andersonkoester** [chrisss404/gnome-shell-ext-SkypeNotification#70]
I received some messages and the extension does not shows the alert icon.
I'm using master rep and Fedora 24 (GNOME 3.20.2).

**Comment by chrisss404** [comment]
Please check, if the following command results in a notification:

    python ~/.local/share/gnome-shell/extensions/SkypeNotification@chrisss404.gmail.com/notify.py -e"ChatIncoming" -n"Test" -f"%fname" -p"%fpath" -m"hello" -s"%fsize" -u"%sskype"

**Comment by andersonkoester** [comment]
Thanks, it was dbus import error.
I already fix python error and it's working fine.
